# Generated by Django 5.2.5 on 2025-08-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fin_mate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="balance",
        ),
    ]
