# Generated by Django 5.2.5 on 2025-08-22 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_mate", "0002_remove_account_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("BLUE", "Blue"),
                            ("RED", "Red"),
                            ("PINK", "Pink"),
                            ("ORANGE", "Orange"),
                            ("KHAKI", "Khaki"),
                            ("PURPLE", "Purple"),
                            ("LIME", "Lime"),
                            ("AQUA", "Aqua"),
                            ("BROWN", "Brown"),
                            ("GRAY", "Gray"),
                            ("BLACK", "Black"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TransactionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="budget",
            options={
                "ordering": ["-period", "category__name"],
                "verbose_name_plural": "budgets",
            },
        ),
        migrations.RemoveConstraint(
            model_name="budget",
            name="uniq_user_category_month",
        ),
        migrations.RemoveConstraint(
            model_name="budget",
            name="budget_limit_gt_than_zero",
        ),
        migrations.RenameField(
            model_name="budget",
            old_name="month",
            new_name="period",
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                fields=("user", "category", "period"), name="uniq_user_category_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(("limit__gt", 0)), name="budget_limit_gt_zero"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="transactiontag",
            name="added_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="transactiontag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fin_mate.tag"
            ),
        ),
        migrations.AddField(
            model_name="transactiontag",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fin_mate.transaction"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="transactions",
                through="fin_mate.TransactionTag",
                to="fin_mate.tag",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "date"], name="fin_mate_tr_account_b5d5a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category", "date"], name="fin_mate_tr_categor_af93ce_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="transaction_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uniq_tag_name_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="transactiontag",
            index=models.Index(
                fields=["transaction"], name="fin_mate_tr_transac_d9353b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactiontag",
            index=models.Index(fields=["tag"], name="fin_mate_tr_tag_id_5eea8f_idx"),
        ),
        migrations.AddConstraint(
            model_name="transactiontag",
            constraint=models.UniqueConstraint(
                fields=("transaction", "tag"), name="uniq_tag_per_transaction"
            ),
        ),
    ]
