# Generated by Django 5.2.5 on 2025-08-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_mate", "0003_tag_transactiontag_alter_budget_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "Blue"),
                    ("secondary", "Gray"),
                    ("success", "Green"),
                    ("danger", "Red"),
                    ("warning", "Yellow"),
                    ("info", "Cyan"),
                    ("dark", "Dark"),
                    ("light", "Light"),
                ],
                default="primary",
                max_length=10,
            ),
        ),
    ]
