# Generated by Django 5.2.5 on 2025-08-25 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_mate", "0004_alter_tag_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="color",
        ),
        migrations.AddField(
            model_name="transactiontag",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "Blue"),
                    ("secondary", "Gray"),
                    ("success", "Green"),
                    ("danger", "Red"),
                    ("warning", "Yellow"),
                    ("info", "Cyan"),
                    ("dark", "Dark"),
                    ("light", "Light"),
                ],
                default="primary",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
    ]
