# Generated by Django 5.2.5 on 2025-08-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_mate", "0005_remove_tag_color_transactiontag_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactiontag",
            name="color",
        ),
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "Blue"),
                    ("secondary", "Gray"),
                    ("success", "Green"),
                    ("danger", "Red"),
                    ("warning", "Yellow"),
                    ("info", "Cyan"),
                    ("dark", "Dark"),
                    ("light", "Light"),
                ],
                default="secondary",
                max_length=10,
            ),
        ),
    ]
