# Generated by Django 5.2.5 on 2025-08-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_mate", "0006_remove_transactiontag_color_tag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "Blue"),
                    ("secondary", "Gray"),
                    ("success", "Green"),
                    ("danger", "Red"),
                    ("warning", "Yellow"),
                    ("info", "Cyan"),
                    ("light", "Light"),
                ],
                default="secondary",
                max_length=10,
            ),
        ),
    ]
