# Generated by Django 5.2.5 on 2025-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_mate", "0007_alter_tag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_system",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
